cabal-version: 3.4
name:          planning-poker
version:       0.1.0.0

common warnings
  ghc-options:
    -Wall -Wcompat -Wincomplete-record-updates
    -Wincomplete-uni-patterns -Wredundant-constraints
    -Wmissing-export-lists -Wpartial-fields

library
  import:             warnings
  hs-source-dirs:     src
  default-language:   Haskell2010
  default-extensions:
    OverloadedStrings
    RecordWildCards

  exposed-modules:
    Core
    Logger
    Paths_planning_poker
    PlanningPoker
    Web
    Web.View

  build-depends:
    , aeson
    , base
    , bytestring
    , directory
    , http-types
    , lens
    , lucid2
    , mtl
    , multipart
    , random
    , scotty         ==0.22
    , sqlite-simple
    , stm
    , text
    , time
    , uuid
    , wai
    , wai-extra
    , yaml

executable planning-poker
  main-is:          Main.hs
  hs-source-dirs:   app
  ghc-options:      -Wall -threaded -rtsopts -with-rtsopts=-N
  default-language: Haskell2010
  build-depends:
    , base
    , planning-poker

test-suite planning-poker-test
  import:           warnings
  default-language: Haskell2010
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  build-depends:
    , base
    , hspec
    , hspec-wai
    , planning-poker
    , QuickCheck
    , quickcheck-instances
    , scotty
    , text
    , uuid
    , wai
